### ISSUE TITLE
cannot start package within a node server

### ISSUE THREAD

**Issue by juanmagomezmayoral** [oblakstudio/qr-code-styling#1]
The documentation says that **qr-code-styling/lib/qr-code-styling.common.js** should be referenced but that file does not exists.

When trying to use it from server it says

**Error: Cannot find module 'qr-code-styling/lib/qr-code-styling.common.js'**

and when i substitute this reference
```Javascript
const { QRCodeStyling } = require("qr-code-styling/lib/qr-code-styling.common.js");
```
for this
```Javascript
const { QRCodeStyling } = require("qr-code-styling/lib/qr-code-styling.js");
```
it says 
**ReferenceError: self is not defined
    at Object.<anonymous> (C:\www\qrGenerator\node\node_modules\qr-code-styling\lib\qr-code-styling.js:1:208)**

**Comment by jchomali** [comment]
> The documentation says that **qr-code-styling/lib/qr-code-styling.common.js** should be referenced but that file does not exists.
> 
> When trying to use it from server it says
> 
> **Error: Cannot find module 'qr-code-styling/lib/qr-code-styling.common.js'**
> 
> and when i substitute this reference
> 
> ```js
> const { QRCodeStyling } = require("qr-code-styling/lib/qr-code-styling.common.js");
> ```
> 
> for this
> 
> ```js
> const { QRCodeStyling } = require("qr-code-styling/lib/qr-code-styling.js");
> ```
> 
> it says **ReferenceError: self is not defined at Object. (C:\www\qrGenerator\node\node_modules\qr-code-styling\lib\qr-code-styling.js:1:208)**

Check this https://www.npmjs.com/package/qr-code-styling-node
Leaving it here in case others encounter this issue.
For implementation, check this issue comment: https://github.com/kozakdenys/qr-code-styling/issues/9#issuecomment-932095337
